urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^report/', include('worklogs.urls')),
    url(r'^', include(admin.site.urls)),
)

urlpatterns += patterns('',
   (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

worklogs/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns, url

from .views import task_start, task_stop, make_tasks, report

urlpatterns = patterns('',
    url(r'^$', report, name='report'),
)

task_admin_urls = patterns('',
    url(r'^start/(?P<object_id>\d+)/$', task_start, name='task_start'),
    url(r'^stop/(?P<object_id>\d+)/$', task_stop, name='task_stop'),
    url(r'^make_tasks/$', make_tasks, name='make_tasks'),
)

worklogs/models.py
# -*- coding: utf-8 -*-

#importy z pythona
import datetime

# importy z django
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse

from .managers import TaskManager, WorkLogManager
from .templatetags.worklogs_tags import seconds_to_readable


def get_total_seconds(td):
    return (td.microseconds + (td.seconds + td.days * 24 * 3600) * 1e6) / 1e6


def firstof(*items):
    for i in items:
        if i:
            return i


class Client(models.Model):

    login = models.CharField(max_length=255, verbose_name=_(u"login"))
    name = models.CharField(max_length=255, verbose_name=_(u"name"))
    position = models.CharField(max_length=255, verbose_name=_(u"position"))
    phone = models.CharField(max_length=255, verbose_name=_(u"phone"))
    email = models.CharField(max_length=255, verbose_name=_(u"email"))
    xmpp = models.CharField(max_length=255, verbose_name=_(u"xmpp"))

    class Meta:
        verbose_name = _(u"client")
        verbose_name_plural = _(u"clients")
        ordering = ['login']

    def __unicode__(self):
        return self.name


class Task(models.Model):
    STATE_NEW = 0
    STATE_IN_PROGRESS = 1
    STATE_WAITING = 2
    STATE_READY = 3
    STATE_RESOLVED = 4
    STATE_CLOSED = 5
    STATE_REJECTED = 6
    STATE_NOTFORME = 7

    STATE_CHOICES = (
        (STATE_NEW, _(u"nowy")),
        (STATE_IN_PROGRESS, _(u"w trakcie")),
        (STATE_WAITING, _(u"czekam")),
        (STATE_READY, _(u"gotowy")),
        (STATE_RESOLVED, _(u"rozwiązany")),
        (STATE_CLOSED, _(u"zamknięty")),
        (STATE_REJECTED, _(u"odrzucony")),
        (STATE_NOTFORME, _(u"dla grafika")),
    )

    active = models.BooleanField(verbose_name=_(u'active'))

    description = models.CharField(
        max_length=1024,
        verbose_name=_(u'description'))

    user = models.ForeignKey('auth.User',
                             verbose_name=_(u'user'),
                             related_name='tasks')

    project = models.ForeignKey('Project',
                                verbose_name=_(u'project'),
                                related_name='tasks',
                                blank=True,
                                null=True)

    bugtracker = models.ForeignKey('BugTracker',
                                   blank=True,
                                   null=True,
                                   verbose_name=_(u'bugtracker'),
                                   related_name='tasks')

    bugtracker_object_id = models.CharField(
        blank=True,
        null=True,
        max_length=16,
        verbose_name=_(u"bugtracker object id"))

    duration = models.PositiveIntegerField(
        blank=True,
        null=True,
        verbose_name=_(u"duration"))

    add_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_(u'date added'))

    mod_date = models.DateTimeField(
        auto_now=True,
        verbose_name=_(u'date modified'))

    state = models.PositiveSmallIntegerField(
        default=STATE_NEW,
        choices=STATE_CHOICES,
        verbose_name=_(u"state"))

    eta = models.DecimalField(
        blank=True,
        decimal_places=4,
        max_digits=8,
        null=True,
        verbose_name=_(u"eta (hours)"))

    client = models.ForeignKey(
        to='Client',
        blank=True,
        null=True,
        verbose_name=_(u"client"))

    objects = TaskManager()

    class Meta:
        verbose_name = _(u'task')
        verbose_name_plural = _(u'tasks')
        ordering = ('-add_date',)
        get_latest_by = 'add_date'

    def __unicode__(self):
        try:
            return "{0}/{1}".format(self.bugtracker.name, self.bugtracker_object_id)
        except AttributeError:
            return "{0}".format(self.description)

    def get_bugtracker_id(self):
        return '#%s' % self.bugtracker_object_id
    get_bugtracker_id.short_description = _(u"#")

    def get_absolute_url(self):
        return reverse('task', args=[self.pk])

    def bugtracker_url(self):
        return self.bugtracker.url_pattern.format(id=self.bugtracker_object_id)

    def start(self, description=None):
        # stop active Task
        Task.objects.stop_active()

        # mark self active
        if self.state == self.STATE_NEW:
            self.state = self.STATE_IN_PROGRESS
        self.active = True
        self.save()

        # create new WorkLog for this Task
        WorkLog.objects.create(task=self, description=description)

    def stop(self):
        try:
            active_entry = self.worklogs.filter(active=True).get()
        except WorkLog.DoesNotExist:
            pass
        else:
            active_entry.stop()

        self.duration = self._calculate_duration()
        self.active = False
        self.save()

    def _calculate_duration(self):
        return sum(map(lambda e: e.duration, self.worklogs.all()))

    def update_duration(self):
        self.duration = self._calculate_duration()
        self.save()

    def time_left(self):
        if self.eta and self.duration:
            return self._seconds_to_readable(int(self.eta * 3600) - self.duration)
    time_left.short_description = _(u"time left")

    def _seconds_to_readable(self, seconds):
        if seconds < 0:
            seconds = -seconds
            negative = True
        else:
            negative = False
        h = seconds / 3600
        m = seconds / 60 % 60
        s = seconds % 60
        #return "{h}:{m}:{s}".format(**locals())
        ret = "{h}h {m}m {s}s".format(**locals())
        if negative:
            ret = '- ' + ret
        return ret

    def get_duration_display(self):
        if self.active or not self.duration:
            self.update_duration()
        return self._seconds_to_readable(self.duration)
    get_duration_display.short_description = _(u"duration")

    def get_eta_display(self):
        if self.eta:
            return self._seconds_to_readable(int(self.eta * 3600))
    get_eta_display.short_description = _(u"eta")


class WorkLog(models.Model):
    active = models.BooleanField(
        default=True,
        verbose_name=_(u'active'))

    description = models.CharField(
        blank=True,
        null=True,
        max_length=1024,
        verbose_name=_(u'description'))

    task = models.ForeignKey('Task',
                             verbose_name=_(u'task'),
                             related_name='worklogs')

    start = models.DateTimeField(
        default=datetime.datetime.now,
        verbose_name=_(u'start time'))

    end = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name=_(u'end time'))

    accounted = models.BooleanField(
        default=False,
        verbose_name=_(u"accounted"))

    objects = WorkLogManager()

    class Meta:
        verbose_name = _(u'worklog')
        verbose_name_plural = _(u'worklogs')
        ordering = ('-start',)
        get_latest_by = 'start'

    def stop(self):
        self.active = False
        self.end = datetime.datetime.now()
        self.save()

    @property
    def duration(self):
        if self.end:
            delta = self.end - self.start
        else:
            delta = datetime.datetime.now() - self.start
        return int(round(get_total_seconds(delta)))

    @duration.setter
    def duration(self, seconds):
        self.end = self.start + datetime.timedelta(seconds=seconds)

    def get_duration_display(self):
        return seconds_to_readable(self.duration)
    get_duration_display.short_description = _(u"duration")


class Project(models.Model):

    active = models.BooleanField(verbose_name=_(u'active'))

    name = models.CharField(
        max_length=64,
        verbose_name=_(u'name'))

    url = models.URLField(
        blank=True,
        null=True,
        verbose_name=_(u"url"))

    class Meta:
        verbose_name = _(u'project')
        verbose_name_plural = _(u'projects')

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project', args=[self.pk])


class BugTracker(models.Model):
    active = models.BooleanField(verbose_name=_(u'active'))

    name = models.CharField(
        max_length=64,
        verbose_name=_(u'name'))

    url_pattern = models.CharField(
        max_length=256,
        verbose_name=_(u'url_pattern'))

    class Meta:
        verbose_name = _(u'bugtracker')
        verbose_name_plural = _(u'bugtrackers')

    def __unicode__(self):
        return self.name


class Note(models.Model):
    task = models.ForeignKey('Task',
                             related_name='notes',
                             verbose_name=_(u"task"))

    note = models.TextField(
        verbose_name=_(u"note"))

    add_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_(u'date added'))

    mod_date = models.DateTimeField(
        auto_now=True,
        verbose_name=_(u'date modified'))

    class Meta:
        verbose_name = _(u'note')
        verbose_name_plural = _(u'notes')

    def __unicode__(self):
        return self.note[:min(60, len(self.note))] + u'...'

worklogs/forms.py
# -*- coding: utf-8 -*-
#import os

from django import forms
#from django.conf import settings
#from django.utils.translation import ugettext_lazy as _

from .models import Task


class TaskAddForm(forms.ModelForm):

    class Meta:
        model = Task
        exclude = ('active', 'duration')

worklogs/views.py
# -*- coding: utf-8 -*-
import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User

from .models import Task, WorkLog
from .rozlicz import _rozlicz

current_year = lambda: datetime.datetime.now().isocalendar()[0]
current_week = lambda: datetime.datetime.now().isocalendar()[1]


def tofirstdayinisoweek(year, week):
    ret = datetime.datetime.strptime('%04d-%02d-1' % (year, week), '%Y-%W-%w')
    if datetime.date(year, 1, 4).isoweekday() > 4:
        ret -= datetime.timedelta(days=7)
    return ret


@login_required
def task_start(request, object_id):
    task = Task.objects.get(id=object_id)
    next = request.GET.get('next', '/')
    if request.user == task.user or request.user.is_superuser:
        # FIXME: zamienic na "user_passes_test"
        task.start()
        messages.success(request, _(u'Task "{0}" has been started.').format(task))
    else:
        messages.error(request, _(u'Task "{0}" has <b>not</b> been started. Insufficient permissions.').format(task))
    return HttpResponseRedirect(next)


@login_required
def task_stop(request, object_id):
    task = Task.objects.get(id=object_id)
    next = request.GET.get('next', '/')
    if request.user == task.user or request.user.is_superuser:
        # FIXME: zamienic na "user_passes_test"
        task.stop()
        messages.success(request, _(u'Task "{0}" has been stopped.').format(task))
    else:
        messages.error(request, _(u'Task "{0}" has <b>not</b> been stopped. Insufficient permissions.').format(task))
    return HttpResponseRedirect(next)


from django import forms


class TasksForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea())

from .mantis import make_mantis_task
import re
from django.shortcuts import render


@login_required
def make_tasks(request):
    next = request.GET.get('next', '/worklogs/task/')
    if request.method == 'POST':
        form = TasksForm(request.POST)
        if form.is_valid():
            tickets = re.findall(r'\d{5,8}', form.cleaned_data.get('message'))
            tickets = set(map(int, tickets))
            for ticket in tickets:
                try:
                    task = make_mantis_task(ticket)
                except Exception, e:
                    messages.error(request, _(u'Task "{0}" nie dodany. {1}').format(ticket, e))
                else:
                    messages.success(request, _(u'Task "{1}" dodany.').format(task.id, task.description))
            return HttpResponseRedirect(next)
    else:
        form = TasksForm()

    return render(request, 'worklogs/make_tasks.html', {
        'form': form,
    })


@login_required
def report(request):

    user = request.user

    get_from_date = request.GET.get('from')
    get_to_date = request.GET.get('to')

    year = current_year()
    week = current_week()

    if get_from_date:
        tmp = map(int, get_from_date.split('-'))
        from_date = datetime.datetime(*tmp)
    else:
        from_date = tofirstdayinisoweek(year, week)

    if get_to_date:
        tmp = map(int, get_to_date.split('-'))
        to_date = datetime.datetime(*tmp)
    else:
        to_date = from_date + datetime.timedelta(days=4)

    entries = WorkLog.objects.in_range(from_date, to_date).filter(task__user=user)

    time_per_project = {}
    time_per_task = []
    tasks_per_day = {}
    worklogs_plot = {}

    for entry in entries:
        try:
            index = list(map(lambda a: a[0].id, time_per_task)).index(entry.task.id)
        except ValueError:
            time_per_task.append([entry.task, entry.duration])
        else:
            time_per_task[index][1] += entry.duration

        date = entry.start.date()
        if date in tasks_per_day:
            try:
                index = list(map(lambda a: a[0].id, tasks_per_day[date]['tasks'])).index(entry.task.id)
            except ValueError:
                tasks_per_day[date]['tasks'].append([entry.task, entry.duration])
            else:
                tasks_per_day[date]['tasks'][index][1] += entry.duration
            tasks_per_day[date]['time'] += entry.duration
        else:
            tasks_per_day[date] = {
                    'time': entry.duration,
                    'tasks': [[entry.task, entry.duration]],
                }

        if entry.task.project in time_per_project:
            time_per_project[entry.task.project]['time'] += entry.duration
            try:
                index = list(map(lambda a: a[0].id, time_per_project[entry.task.project]['tasks'])).index(entry.task.id)
            except ValueError:
                time_per_project[entry.task.project]['tasks'].append([entry.task, entry.duration])
            else:
                time_per_project[entry.task.project]['tasks'][index][1] += entry.duration
        else:
            time_per_project[entry.task.project] = {
                    'time': entry.duration,
                    'tasks': [[entry.task, entry.duration]],
                }

        # worklogs_plot

        ticket = "{0}{1}".format(entry.task.bugtracker.name, entry.task.bugtracker_object_id)
        start = entry.start
        end = entry.end if entry.end else datetime.datetime.now()
        row = (start, end)
        if ticket in worklogs_plot:
            worklogs_plot[ticket].append(row)
        else:
            worklogs_plot[ticket] = [row]

    tasks = Task.objects.filter(add_date__gte=from_date, add_date__lte=to_date)

    context_vars = {
        'tasks': tasks,
        'from': from_date.date(),
        'to': to_date.date(),
        'tasks_per_day': tasks_per_day,
        'time_per_project': time_per_project,
        'time_per_task': time_per_task,
        'tasks_by_status': sorted(time_per_task, key=lambda x: x[0].state),
        'worklogs_plot': worklogs_plot,
        'worklogs_plot_start': from_date.date() - datetime.timedelta(days=1),
        'worklogs_plot_end': to_date.date() + datetime.timedelta(days=1),
    }
    return render_to_response('worklogs/report.html', context_vars)


@login_required
def rozlicz(request, object_id):
    task = Task.objects.get(id=object_id)
    next = request.GET.get('next', '/')
    result = _rozlicz(task)
    if not result:
        messages.success(request, _(u'Task "{0}" accounted.').format(task))
    else:
        messages.error(request, _(u'Task "{0}" has`t been accounted. {1}').format(task, result))
    return HttpResponseRedirect(next)

templates/worklogs/base.html
{% extends "base.html" %}

templates/worklogs/make_tasks.html
{% extends "admin/change_form.html" %}

{% block breadcrumbs %}
{% endblock %}


{% block content %}
<div id="content-main">
<form action="." method="post" accept-charset="utf-8">
    {% csrf_token %}
{{ form.as_p }}
    <p><input type="submit" value="Continue →"></p>
</form>
</div>
{% endblock %}

templates/worklogs/report.html
{% extends "base.html" %}
{% load worklogs_tags i18n static %}

{% block extrahead %}
<link rel="stylesheet" href="{% static "themes/base/jquery.ui.all.css" %}">
<link rel="stylesheet" href="{% static "styles/demos.css" %}">
<script src="{% static "scripts/jquery-1.7.2.js" %}"></script>
<script src="{% static "scripts/jquery.cookie.js" %}"></script>
<script src="{% static "scripts/ui/jquery.ui.core.js" %}"></script>
<script src="{% static "scripts/ui/jquery.ui.widget.js" %}"></script>
<script src="{% static "scripts/ui/jquery.ui.mouse.js" %}"></script>
<script src="{% static "scripts/ui/jquery.ui.sortable.js" %}"></script>
<script src="{% static "scripts/ui/jquery.ui.tabs.js" %}"></script>
<script src="{% static "scripts/ui/jquery.ui.datepicker.js" %}"></script>
<script>
	$(document).ready(function() {
		var tabs = $( "#reports" ).tabs({
			cookie: {expires: 1}
		});
		tabs.tabs().find( ".ui-tabs-nav" ).sortable({
			axis: "x"
		});
		var dates = $( "#from, #to" ).datepicker({
			changeMonth: true,
			changeYear: true,
			maxDate: "+0D",
			firstDay: 1,
			dateFormat: 'yy-mm-dd',
			onSelect: function( selectedDate ) {
				var option = this.id == "from" ? "minDate" : "maxDate",
				instance = $( this ).data( "datepicker" ),
				date = $.datepicker.parseDate(
				instance.settings.dateFormat ||
				$.datepicker._defaults.dateFormat,
				selectedDate, instance.settings );
				dates.not( this ).datepicker( "option", option, date );
			}
		});
		$("textarea.copy").each(function(){
			var rows = this.value.split("\n").length;
			this.setAttribute('rows', rows + 1);
		});
	});
</script>
<style>
	textarea.copy {
		font-family: monospace;
		font-size: 12px;
		border: none;
	}
</style>

{% endblock %}

{% block content %}
<div class="demo">
	<form method="GET">
		<label for="from">From</label>
		<input type="text" id="from" name="from" value="{{ from.isoformat }}"/>
		<label for="to">to</label>
		<input type="text" id="to" name="to" value="{{ to.isoformat }}"/>
		<input type="submit" />
	</form>
	{% if time_per_task %}
	<div id="reports">
		<ul>
			<li><a href="#time_per_task">{% trans "time per task" %}</a></li>
			<li><a href="#tasks_status">{% trans "tasks status" %}</a></li>
			<li><a href="#tasks_per_day">{% trans "tasks per day" %}</a></li>
			<li><a href="#time_per_project">{% trans "time per project" %}</a></li>
			<li><a href="#tasks_eta">{% trans "tasks eta" %}</a></li>
			<li><a href="#tasks_per_project">{% trans "tasks per project" %}</a></li>
		</ul>
		<div id="time_per_task">
			<textarea class="copy" rows="24" cols="80">{% if from != to %}{{ from }} - {{ to }}
{% endif %}{% for task, duration in time_per_task %}
{{ task.description }} ({{duration|seconds_to_time}}) - {{ task.get_state_display }}
{{ task.bugtracker_url }}
{% endfor %}</textarea>
		</div>
		<div id="tasks_status">
			<textarea class="copy" rows="24" cols="80">{% if from != to %}{{ from }} - {{ to }}
{% endif %}{% for task, duration in tasks_by_status %}
{{ task.description }} - {{ task.get_state_display }}
{{ task.bugtracker_url }}
{% endfor %}</textarea>
		</div>

		<div id="tasks_per_day">
			<textarea class="copy" rows="24" cols="80">{% if from != to %}{{ from }} - {{ to }}
{% endif %}{% for date, data in tasks_per_day.items %}
{{ date }} ({{ data.time|seconds_to_time }}):
{% for task, duration in data.tasks %}
{{ task.description }} ({{duration|seconds_to_time}})
{{ task.bugtracker_url }}
{% endfor %}{% endfor %}</textarea>
		</div>
		<div id="time_per_project">
			<textarea class="copy" rows="24" cols="80">{% if from != to %}{{ from }} - {{ to }}
{% endif %}{% for project, data in time_per_project.items %}
{{ project }}: {{ data.time|seconds_to_hours:2|floatformat }}h{% endfor %}</textarea>
		</div>
		<div id="tasks_eta">
			<textarea class="copy" rows="24" cols="80">{% for task in tasks %}{{ task.bugtracker_url }}: {{ task.eta }}h
{% endfor %}</textarea>
		</div>
        <div id="tasks_per_project">
            {% regroup tasks by project as tasks_per_project %}
			<textarea class="copy" rows="24" cols="80">{% if from != to %}{{ from }} - {{ to }}
{% endif %}{% for project in tasks_per_project %}
{{ project.grouper }}:
{% for task in project.list %}
{{ task.description }} - {{ task.get_state_display }}
{{ task.bugtracker_url }}
{% endfor %}{% endfor %}</textarea>
		</div>
	</div>
	{% else %}
	{% trans "No tasks in selected date range" %}
	{% endif %}
</div>
{% endblock %}

templates/worklogs/worklog_archive_day.html
{% extends "worklogs/base.html" %}

{% block content %}
{{ object_list|pprint }}
{% endblock content %}

templates/worklogs/worklog_list.html
{% extends "worklogs/base.html" %}

{% block content %}
{{ object_list|pprint }}
{% endblock content %}